import { useState } from 'react'
import { useNavigate } from 'react-router'
import { useAuth } from '../contexts/AuthContext.jsx'
import { useCart } from '../contexts/CartContext.jsx'
export default function Checkout() {
  const navigate = useNavigate(); const { user } = useAuth(); const { items, total, clearCart } = useCart()
  const [form, setForm] = useState({ nombre: user?.nombre || '', email: user?.email || '', direccion: '', entrega: 'Estándar' })
  function submit(event) { event.preventDefault(); if (!items.length || !form.direccion.trim()) { navigate('/compra-fallida'); return } clearCart(); window.localStorage.setItem('resenasmixx.lastPurchase', JSON.stringify({ ...form, total: total(), fecha: new Date().toISOString() })); navigate('/compra-exitosa') }
  return <div className="container"><h1 className="page-title h2">Checkout</h1><p className="text-muted-soft">Los datos disponibles de la sesión se cargan automáticamente.</p><div className="row g-4"><div className="col-lg-7"><form className="form-panel p-4" onSubmit={submit}><label className="form-label">Nombre</label><input className="form-control mb-3" value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} required /><label className="form-label">Email</label><input type="email" className="form-control mb-3" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><label className="form-label">Dirección de envío</label><textarea className="form-control mb-3" rows="3" value={form.direccion} onChange={(e) => setForm({ ...form, direccion: e.target.value })} required /><label className="form-label">Entrega</label><select className="form-select mb-4" value={form.entrega} onChange={(e) => setForm({ ...form, entrega: e.target.value })}><option>Estándar</option><option>Express</option></select><button className="btn btn-cyan w-100">Confirmar compra simulada</button></form></div><div className="col-lg-5"><div className="hero-panel p-4"><h2 className="h5">Resumen</h2><p className="text-muted-soft">{items.length} producto(s)</p><div className="display-6 fw-bold text-cyan">${total().toLocaleString('es-CL')}</div></div></div></div></div>
}
